version: '3.1'

services:
  nestjs:
    build: .
    ports:
      - ${NESTJS_PORT}:${NESTJS_PORT}
    env_file:
      - .env
    networks:
      - mynetwork
    
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app

  mongo:
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    networks:
      - mynetwork
  
networks:
  mynetwork: